### ISSUE TITLE
Only sorts the first instance

### ISSUE THREAD

**Issue by mattiasb** [rweir/auto-sort-mode#2]
If I have multiple sorted regions in a file `auto-sort-mode` will only sort the first.

Example 1 (Before saving):
```yaml
---
sorted-1:
  # sort-start
  - Tree
  - Ball
  - Ladder
  # sort-end

unsorted:
  - Tree
  - Ball
  - Ladder

sorted-2:
  # sort-start
  - Tree
  - Ball
  - Ladder
  # sort-end
```

Example 2 (After saving):
```yaml
---
sorted-1:
  # sort-start
  - Ball
  - Ladder
  - Tree
  # sort-end

unsorted:
  - Tree
  - Ball
  - Ladder

sorted-2:
  # sort-start
  - Tree
  - Ball
  - Ladder
  # sort-end
```
Note how the `sorted-2` list still has unsorted elements.
